AWSTemplateFormatVersion: '2010-09-09'
Description: 'Book Q&A API Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess

  BookQALambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: query_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          # Lambda function code will be deployed separately
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          EMBEDDINGS_TABLE: !Ref EmbeddingsTable
          ENVIRONMENT: !Ref Environment

  BookQAAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'book-qa-api-${Environment}'
      Description: 'API for Book Q&A application'

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BookQAAPI
      ParentId: !GetAtt BookQAAPI.RootResourceId
      PathPart: 'query'

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BookQAAPI
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BookQALambda.Arn}/invocations'

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      RestApiId: !Ref BookQAAPI

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref BookQAAPI
      DeploymentId: !Ref ApiGatewayDeployment
      StageName: !Ref Environment

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BookQALambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BookQAAPI}/*/*/*'

  EmbeddingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'book-embeddings-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chunk_id
          AttributeType: S
        - AttributeName: book_title
          AttributeType: S
      KeySchema:
        - AttributeName: chunk_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: book_title-index
          KeySchema:
            - AttributeName: book_title
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${BookQAAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/query'
  LambdaFunctionArn:
    Description: 'Lambda function ARN'
    Value: !GetAtt BookQALambda.Arn
  EmbeddingsTableName:
    Description: 'DynamoDB table name for embeddings'
    Value: !Ref EmbeddingsTable 