AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Vectors Infrastructure for Epic Library'

Parameters:
  VectorBucketName:
    Type: String
    Default: 'epic-s3-vectors-bucket'
    Description: 'Name for the S3 Vector bucket'

  VectorIndexName:
    Type: String
    Default: 'epic-book-embeddings-index'
    Description: 'Name for the vector index'

Resources:
  # S3 Vector Bucket
  VectorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref VectorBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # Vector Index
  VectorIndex:
    Type: Custom::VectorIndex
    Properties:
      ServiceToken: !GetAtt VectorIndexFunction.Arn
      BucketName: !Ref VectorBucketName
      IndexName: !Ref VectorIndexName
      IndexConfiguration:
        VectorConfiguration:
          Dimension: 1536
          MetricType: COSINE
        MetadataConfiguration:
          FilterableMetadata:
            - book_title
            - chunk_id
            - chunk_number
          NonFilterableMetadata:
            - text

  # Lambda function to create vector index
  VectorIndexFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: epic-vector-index-creator
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt VectorIndexRole.Arn
      Timeout: 60
      MemorySize: 128
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          
          def handler(event, context):
              try:
                  if event['RequestType'] in ['Create', 'Update']:
                      s3_vectors = boto3.client('s3vectors')
                      
                      response = s3_vectors.create_index(
                          vectorBucketName=event['ResourceProperties']['BucketName'],
                          indexName=event['ResourceProperties']['IndexName'],
                          indexConfiguration=event['ResourceProperties']['IndexConfiguration']
                      )
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                          'IndexArn': response.get('IndexArn', '')
                      })
                  else:
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  # IAM Role for Vector Index Creator
  VectorIndexRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: epic-vector-index-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3VectorsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3vectors:CreateIndex
                  - s3vectors:DeleteIndex
                  - s3vectors:DescribeIndex
                  - s3vectors:GetIndex
                  - s3vectors:ListIndexes
                Resource: '*'

  # IAM Role for Lambda Functions (Updated with S3 Vectors permissions)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: epic-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: S3VectorsLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3vectors:CreateBucket
                  - s3vectors:CreateIndex
                  - s3vectors:PutObject
                  - s3vectors:Search
                  - s3vectors:GetObject
                  - s3vectors:DeleteObject
                  - s3vectors:ListBuckets
                  - s3vectors:ListIndexes
                  - s3vectors:DescribeIndex
                Resource: '*'

Outputs:
  VectorBucketName:
    Description: 'Name of the S3 Vector bucket'
    Value: !Ref VectorBucketName
    Export:
      Name: !Sub '${AWS::StackName}-VectorBucketName'

  VectorIndexName:
    Description: 'Name of the vector index'
    Value: !Ref VectorIndexName
    Export:
      Name: !Sub '${AWS::StackName}-VectorIndexName'

  LambdaExecutionRoleArn:
    Description: 'ARN of the Lambda execution role with S3 Vectors permissions'
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRoleArn' 